### ISSUE TITLE
Strange server error 500 related to the Complete multipart upload call - debug options?

### ISSUE THREAD

**Issue by bennomeyer** [zdresearch/s3-multipart-upload-javascript-browser#2]
I was able to get this code working. However, I encounter a strange server error related to the complete multipart upload call below but only with files larger than 1MB. I get a error 500 from the server which aborts the upload. Strangely enough sometimes at random it works also with these bigger files. 

It's a hosted server that runs Apache 2.4. 

```
/**
 * Complete multipart upload
 */
S3MultiUpload.prototype.completeMultipartUpload = function () {
    var self = this;
    if (this.completed) return;
    this.completed = true;
    $.post(self.SERVER_LOC, {
        command: 'complete',
        sendBackData: self.sendBackData
    }).done(function (data) {
        self.onUploadCompleted(data);
    }).fail(function (jqXHR, textStatus, errorThrown) {
        self.onServerError('complete', jqXHR, textStatus, errorThrown);
    });
};
```

I believe that the two related calls in the code below to the API are interrupted because of somehow faulty PHP. It seems that the first call `listParts` does not correctly return the `[MultipartUpload][Parts]` array. 

```
if ($command=="complete")
{
    $partsModel = s3("listParts",[
        'Bucket' => bucket(),
        'Key' => $_REQUEST['sendBackData']['key'],
        'UploadId' => $_REQUEST['sendBackData']['uploadId']
    ]);


    $model = s3("completeMultipartUpload",[
        'Bucket' => bucket(),
        'Key' => $_REQUEST['sendBackData']['key'],
        'UploadId' => $_REQUEST['sendBackData']['uploadId'],
        'MultipartUpload' => [
            "Parts"=>$partsModel["Parts"],
        ],
    ]); 

    json_output([
        'success' => true,
        'tmp' => $partsModel,
        'err' => $err,
    ]);
}
```

I checked my server error logs and found the following entries. Sadly, I have no clue what those mean or how to fix it. My guess would be something related to the server's PHP config since files lighter than 1MB work fine. 

``` [Thu Jul 11 11:50:28.374937 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: #2 /home/{SERVER}/vendor/aws/aws-sdk-php/src/S3/S3Client.php(471): Aws\\S3\\S3Client::Aws\\S3\\{closure}(Object(Aws\\Command), NULL), referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374912 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: Stack trace:, referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374946 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: #3 /home/{SERVER}/vendor/aws/aws-sdk-php/src/S3/S3Client.php(405): Aws\\S3\\S3Client::Aws\\S3\\{closure}(Object(Aws\\Command), NULL), referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374929 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: #1 /home/{SERVER}/vendor/aws/aws-sdk-php/src/S3/S3Client.php(448): Aws\\Middleware::Aws\\{closure}(Object(Aws\\Command), NULL), referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374954 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: #4 /home/{SERVER}/vendor/aws/aws-sdk-php/src/S3/S3Client.php(424): Aws\\S3\\S3Client::Aws\\S3\\{closu in /home/{SERVER}/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 65, referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374920 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: #0 /home/{SERVER}/vendor/aws/aws-sdk-php/src/Middleware.php(78): Aws\\Api\\Validator->validate('CompleteMultipa...', Object(Aws\\Api\\StructureShape), Array), referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374866 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: PHP Fatal error:  Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the CompleteMultipartUpload operation:, referer https://{SERVER}/index.php
[Thu Jul 11 11:50:28.374902 2019] [-:error] [pid 75454:tid 34653916160] [client XX.XX.XXX.X:XXXXX] FastCGI: server "/var/run/hcgi/9517" stderr: [MultipartUpload][Parts] must be an array. Found NULL in /home/{SERVER}/vendor/aws/aws-sdk-php/src/Api/Validator.php:65, referer https://{SERVER}/index.php
```

Any ideas what could cause this error or how to debug the server issue? Thanks in advance!

**Comment by abiusx** [comment]
I remember seeing the same error when I tested it.
Unfortunately I don't recall exactly why it happened.

Perhaps the `sendBackData` with `uploadId` and `key` is not sent properly by the client?

**Comment by bennomeyer** [comment]
`key` and `uploadId` seems to be sent to the server according to the request headers, however, I don't know if the server even makes the `listParts` call to S3. The `$partsModel` variable seems to be empty and therefor the `[MultipartUpload][Parts]` is no array which throughs the PHP Fatal error.

**Comment by Ludovic36** [comment]
Hi, i've got the same error, it fails randomly printing that error: Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the CompleteMultipartUpload operation: [MultipartUpload][Parts] must be an array.

But sometimes it's working as expected!  Have you found any fix to have it working? It drives me crazy! Thanks!

**Comment by abiusx** [comment]
No, but now with 3 people having the same issue, it's official!

Maybe AWS sometimes doesn't return anything?

**Comment by Ludovic36** [comment]
Are you in the default zone? i'm in the EU (Paris), i saw other issues related to buckets zone. My website is hosted on EC2. Strange...

**Comment by abiusx** [comment]
Try to add some logging around the results from AWS. I suspect sometimes it's missing some parameters in the result.

**Comment by Ludovic36** [comment]
I found a very strange behavior of the completeMultipartUpload function with no sense at all for me...

The following request is returning back the result of the upload. However when the file is uploaded successfully, i get "FAIL" in console and when the file is not uploaded i get "DONE". Any idea?

$.post(self.SERVER_LOC, {
        command: 'complete',
        sendBackData: self.sendBackData
    }).done(function (data) {
        console.log("done")
        self.onUploadCompleted(data);
    }).fail(function (jqXHR, textStatus, errorThrown) {
        console.log("fail")
        self.onServerError('complete', jqXHR, textStatus, errorThrown);
    });

**Comment by Ludovic36** [comment]
This listPart function seems to have an issue, the object returned sometimes doesn't include the [MultipartUpload][Parts] array

```
$partsModel = s3("listParts",[
            'Bucket' => $my_bucket,
            'Key' => $_REQUEST['sendBackData']['key'],
            'UploadId' => $_REQUEST['sendBackData']['uploadId'],
        ]);

```
```
[Parts] => Array
            (
                [0] => Array
                    (
                        [PartNumber] => 1
                        [LastModified] => Aws\Api\DateTimeResult Object
                            (
                                [date] => 2019-08-06 10:02:36.000000
                                [timezone_type] => 2
                                [timezone] => Z
                            )

                        [ETag] => "69f3fffaf5ea92ab4de10ad56482a088"
                        [Size] => 19200
                    )

            ) 
```

That missing array produces the error message [MultipartUpload][Parts] must be an array. When it does include it everything is working as expected. I tried to compare the parts sent in fail and success cases and they are identical, same file uploading. Only the response from de server change randomly.

I will have to find another way of uploading files to S3 instead of using this code. If anybody has an alternative it would be welcome!

**Comment by abiusx** [comment]
If you repeat the call to this function, would it still fail?

**Comment by Ludovic36** [comment]
Thanks to AbiusX for his time, here is the fix for the error:

What he suggests to do is, add the following before $model = in the complete part:

```
if (!isset($partsModel['Parts']))
{
	sleep(2);
        $partsModel = s3("listParts",[
            'Bucket' => bucket(),
            'Key' => $_REQUEST['sendBackData']['key'],
            'UploadId' => $_REQUEST['sendBackData']['uploadId'],
        ]);
}
```

And it works perfectly!

Thanks!

**Comment by bennomeyer** [comment]
Thank you both for helping with this issue! That solves it!

**Comment by abiusx** [comment]
I don't like the solution as it is a bit ugly.
An exponential usleep until 2 seconds would probably be a nicer solution, starting at 100ms.
 Lets keep the issue open so that I can do the PR.
-A

**Comment by dbeja** [comment]
Are there any updates on this issue? Thanks

**Comment by abiusx** [comment]
I have not worked on it, but the time delay solution seems to be working.

**Comment by dbeja** [comment]
Yes, I started now using it.
Just checking if you come up with a "prettier" solution.
Thanks for the update.

**Comment by Ludovic36** [comment]
Using the fix by abiusx, avoid this error. i didn't had any more issues of that type since i'm using it. So it does the trick perfectly. In my case having to wait 2 seconds to validate the upload is not a problem.

**Comment by code-runner-2017** [comment]
Hi, I'm not sure if can be related to this problem, but there is a discussion about listParts not reliable enough to complete MultipartUpload here:

[https://github.com/aws/aws-sdk-go/issues/1518](https://github.com/aws/aws-sdk-go/issues/1518)

It is about the GO language, but if the issue is on the AWS server-side, it applies to PHP too.

**Comment by Ludovic36** [comment]
Yes i confirm this error is related to listParts. The fix using sleep(2) did work until now on normal internet speed but it failed with new tests on low speed. The only way as Amazon suggests is to generate our own ETags for each uploaded parts and then pass the array to completeMultipartUpload to complete the function. I’m trying to find a way of doing it. If somebody already found a way of doing it...

**Comment by abiusx** [comment]
What has the low speed? your server or client? What if you make that sleep 5 seconds? It shuold be way easier than generating ETags!

**Comment by Ludovic36** [comment]
Hi, my client is slow, i can get it working using sleep(30) but sleep(10) fails most of the time. Having to wait 30 seconds after a small file upload is not convenient. If for some reason one part is not uploaded correctly and fails, we can't detect it without creating a list of parts uploaded to compare it with the "listParts" result before executing "completeMultipartUpload", that's why i'm trying to generate ETags while uploading instead of trying to wait the return of "listParts". 

AWS doesn't explain how to do that, on the documentation they only say: "_Only use the returned listing for verification. You should not use the result of this listing when sending a complete multipart upload request. Instead, maintain your own list of the part numbers you specified when uploading parts and the corresponding ETag values that Amazon S3 returns._"

Few posts on Stackoverflow are generating ETags: [like this one](https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb) but for the moment i can't have it working cause the implementation is different like this script...

**Comment by abiusx** [comment]
I get the algorithm, but we need to calculate the ETag on the browser, as we're not uploading the file to our servers. That would put serious computational burdens on the browser for large files.

But lets say we do that. What do we do next with the ETag?

**Comment by Ludovic36** [comment]
Having an array of ETags and part numbers uploaded we can pass it to the "completeMultipartUpload" instead of passing the result of "listParts" to finalize the upload. (If i understand well the process). I found in the S3 API a function called "extractETag" and it seems that this function is not used nowhere, maybe S3 already have a built in solution in order to do that

**Comment by abiusx** [comment]
So what is the current problem with listParts? Is it for failed part uploads, or it just takes some time for them to get processed in S3? I can try the ETag solution,  but I need a reliable way to reproduce the problem first to test.

**Comment by Ludovic36** [comment]
The time needed to process is important but i can add a message to my users on the front end saying "processing upload please wait, do not close the browser" at the end of the upload and during the extra time waiting for listParts return. That's not so "nice" but it would work. The really big issue will be with fail parts as we assuming parts will never fail during the upload. I tested it during month using a high speed optic fiber connexion and it really does the job until i tried with a low adsl connexion and the uploads are most of the time incomplete but processed as successful. That produces a corrupted file as we bypass the integrity checking process. 

In our scenario with a fail, if a User A send a file to User B, User B will received an incomplete file but User A think his file has been send successfully. So, User B will have to contact us to inform that his file is corrupted and we will have to contact User A to ask him to upload again the same file to User B.... a headache and an unsustainable solution!

**Comment by abiusx** [comment]
I see. So we need to add integrity checks to the process too. Doesn't S3 already tell us if the upload part failed?

**Comment by Ludovic36** [comment]
We can check which part have failed comparing our own generated array of parts uploaded containing ETags and part numbers with the returned listParts array. If the ETag generated is the same than the ETag returned and the part number associated to it, then the part has been uploaded successfully. If we send a 4 parts file and we get only 3 parts returned, then we know some part has failed and we need to reupload that specific part. If some part has a different ETag, we can deduce that this part has failed too and we need to reupload that part. That's the way Amazon check integrity of files uploaded and that's the reason why listParts function can't be used to execute completeMultipartUpload. This process is logical but the creation of our own array of ETags is not documented anywhere... Google Storage works based on the same concept and i was able to find much more information to [verify files integrities](https://cloud.google.com/storage/docs/hashes-etags) but hard to implement in this script as it work differently.

**Comment by abiusx** [comment]
My only concern is that because all of this is happening on user's browser, we need to generate ETags there and send them to our server separately. The server cannot calculate them, and thus needs to trust the browser.

But again, to be able to test any of that I need a snippet of code or environment that reliably fails. I cannot reproduce the problem at the moment, even with slow simulation on Chrome.

**Comment by Ludovic36** [comment]
To reproduce a fail maybe you don't need a bad connexion, maybe changing randomly a value of a returned ETag could do the trick. Let say we upload a file in 3 chunks and we generate this following array:

[generatedParts] => Array
            (
                [0] => Array
                    (
                        [PartNumber] => 1
                        [ETag] => "69f3fffaf5ea92ab4de10ad56482a088-1"
                        [Size] => 50000
                    )
                [1] => Array
                    (
                        [PartNumber] => 2
                        [ETag] => "HezxAB2QQWmTRCHMWIGMS8gEcGNLk3dR-2"
                        [Size] => 50000
                    )
                [2] => Array
                    (
                        [PartNumber] => 3
                        [ETag] => "qvYF6TJNCrtqP6AekQ9I24eUJf5aGUXU-3"
                        [Size] => 19200
                    )
            ) 

Instead of comparing with the result of listParts we just compare with the same array but changing the first ETag randomly:

Result of listParts should be:
[Parts] => Array
            (
                [0] => Array
                    (
                        [PartNumber] => 1
                        [ETag] => "XXXXXXXXXXXXXXXXXXXXXX-1"
                        [Size] => 50000
                    )
                [1] => Array
                    (
                        [PartNumber] => 2
                        [ETag] => "HezxAB2QQWmTRCHMWIGMS8gEcGNLk3dR-2"
                        [Size] => 50000
                    )
                [2] => Array
                    (
                        [PartNumber] => 3
                        [ETag] => "qvYF6TJNCrtqP6AekQ9I24eUJf5aGUXU-3"
                        [Size] => 50000
                    )
            ) 

 That's should simulate a part upload issue.

**Comment by abiusx** [comment]
But that's not the original issue, so I cannot have any idea whether I have fixed it or not!
It's a hand made issue that I am fixing by hand :D

**Comment by Ludovic36** [comment]
yes you are right! For last validation tests i can run tests myself with my bad connexion using large files until an error occurs. (From my location it's on every large files uploaded).

**Comment by abiusx** [comment]
Can you quantify that? I'd need to reproduce to be able to code it. What is a large file, what location is that, and what is the speed and latency of the connection?
You can see thsoe on Chrome's Network tab in Developer Tools.

**Comment by Ludovic36** [comment]
Here i send you some checks:

Large file size (for my slow connexion): 89.9Mb
queuing: 1.08ms
Stalled: 9.7min
DNS lookup: 91.43ms
Initial connexion: 185.52ms
SSL: 185.08ms
Request sent: 16.40min
Waiting: 10.20s
Content download: 0.58ms
Uploading total time: 26.3min

Location: Bagnols sur cèze France
Bucket zone: Paris France

**Comment by dipenchand** [comment]
Same issue happened to me.
When I used my company's bucket settings, it works. But If I used my own s3 bucket settings, it won't work.
So, I might missed something in my s3 bucket setup.
```
key: "Uploads/2020/12/dwr1TyUxGMAW1GM14110120.mp4"
parts: []
uploadId: "hgUCx2HkGddvuo9cjYpWG15Oy.40n9V6
```

**Comment by dipenchand** [comment]
Finally, I fixed it adding `eTag` in **CORS Policy** in my bucket:
```
"ExposeHeaders": ["ETag"],
```
