### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by ilyesm** [zdresearch/s3-multipart-upload-javascript-browser#3]
Hi,

When running the script, I am getting error "405 Method not allowed" at the console for a PUT method on line 140 of s3upload.js:

`    request.send(blob);`

Any help? Thanks!

**Comment by abiusx** [comment]
Hello,
How are you running the script?

**Comment by ilyesm** [comment]
Opening the page.htm file on Google Chrome, and trying to upload a file.

**Comment by abiusx** [comment]
You'd need a server setup with the corresponding PHP  files to handle the communicate to AWS from your server too!

**Comment by ilyesm** [comment]
I have the index.php and s3upload.js files, is that not enough?

**Comment by abiusx** [comment]
No you have to provide your AWS credentials in the PHP file. Please take a quick look at it, the code is simple.

**Comment by ilyesm** [comment]
I did do that. Below is the code snippet from index.php.
`if (file_exists("keys.php"))
    require_once "keys.php";
else
{
    function aws_key(){
        return '****';
    }
    function aws_secret(){
        return '****';
    }
    function bucket() {
        return "****";
    }
}`

**Comment by ilyesm** [comment]
I do not have a keys.php file on the directory

**Comment by abiusx** [comment]
Then please replace *** with actual values of key and secret and bucket name!

**Comment by ilyesm** [comment]
On my actual index.php file on my server they are the actual values, I don't want to post them on Github though... Any idea as to why we're getting this error?

**Comment by abiusx** [comment]
I'm not sure then. Would need to have the entire code to be able to test.

Were you able to do uploads via aws-cli using those credentials?

**Comment by nav347** [comment]
is PUT an allowedmethod in the bucket's CORS config?
